apiVersion: apps/v1
kind: Deployment
metadata:
  name: openmanus-backend
  namespace: openmanus-production
  labels:
    app: openmanus
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: openmanus
      component: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: openmanus
        component: backend
    spec:
      containers:
      - name: backend
        image: openmanus/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: database_url
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: mongodb_url
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: secret_key
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: openmanus-config
              key: environment
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: openmanus-config
              key: log_level
        - name: ANTHROPIC_API_KEY
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: anthropic_api_key
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: openai_api_key
        - name: GHL_API_KEY
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: ghl_api_key
        - name: GHL_LOCATION_ID
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: ghl_location_id
        - name: KICKSERV_API_KEY
          valueFrom:
            secretKeyRef:
              name: openmanus-secrets
              key: kickserv_api_key
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: openmanus-logs-pvc 